### ISSUE TITLE
502 gateway error (when start interview)

### ISSUE THREAD

**Issue by amekala** [amekala/mockeryai-local-stable#1]
@07rjain 
Getting 502 gateway error when interview is about to start.
1. improve the sub processes to follow async approach.
2. pdf to text, resume summary, creating message to add to thread etc. try asyncio

i keep getting bad gateway 502 error

<html>
<head><title>502 Bad Gateway</title></head>
<body>
<center><h1>502 Bad Gateway</h1></center>
<hr><center>nginx/1.22.1</center>
</body>
</html>

**Comment by 07rjain** [comment]
can you share the screenshot, i am not able to recreate the error at my end

**Comment by amekala** [comment]
i increased the proxy timeouts and SSL handshakes, so it not happening since then.

        proxy_cache_bypass $http_upgrade;
        proxy_connect_timeout 75s;
        proxy_send_timeout 75s;
        proxy_read_timeout 75s;


        ssl_session_cache shared:SSL:10m; 
        ssl_session_timeout 10m; 
        keepalive_timeout 65;
